services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: importer_example
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - ./app:/opt/app

    queue:
        container_name: importer_queue
        image: rabbitmq:3
