imports:
    - { resource: '../src/Core/Resources/config/services.yaml' }
    - { resource: '../src/Importer1/Resources/config/services.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
